/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */


JNIEXPORT jint JNICALL Java_com_rockchip_devicetest_checkvendor_CheckVendor_check
(JNIEnv *, jobject);

int check_vendor(void);
